// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package task_rpc_config is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Params
	Tasks
	SingleStatus
*/
package task_rpc_config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Params struct {
	ParamsStr string `protobuf:"bytes,1,opt,name=ParamsStr" json:"ParamsStr,omitempty"`
}

func (m *Params) Reset()                    { *m = Params{} }
func (m *Params) String() string            { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()               {}
func (*Params) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Params) GetParamsStr() string {
	if m != nil {
		return m.ParamsStr
	}
	return ""
}

type Tasks struct {
	Content string `protobuf:"bytes,1,opt,name=Content" json:"Content,omitempty"`
}

func (m *Tasks) Reset()                    { *m = Tasks{} }
func (m *Tasks) String() string            { return proto.CompactTextString(m) }
func (*Tasks) ProtoMessage()               {}
func (*Tasks) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Tasks) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SingleStatus struct {
	ErrMessage string `protobuf:"bytes,1,opt,name=ErrMessage" json:"ErrMessage,omitempty"`
}

func (m *SingleStatus) Reset()                    { *m = SingleStatus{} }
func (m *SingleStatus) String() string            { return proto.CompactTextString(m) }
func (*SingleStatus) ProtoMessage()               {}
func (*SingleStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SingleStatus) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "task_rpc_config.Params")
	proto.RegisterType((*Tasks)(nil), "task_rpc_config.Tasks")
	proto.RegisterType((*SingleStatus)(nil), "task_rpc_config.SingleStatus")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Task service

type TaskClient interface {
	QueryTasks(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Tasks, error)
	InsertTasks(ctx context.Context, in *Tasks, opts ...grpc.CallOption) (*SingleStatus, error)
}

type taskClient struct {
	cc *grpc.ClientConn
}

func NewTaskClient(cc *grpc.ClientConn) TaskClient {
	return &taskClient{cc}
}

func (c *taskClient) QueryTasks(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Tasks, error) {
	out := new(Tasks)
	err := grpc.Invoke(ctx, "/task_rpc_config.Task/QueryTasks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) InsertTasks(ctx context.Context, in *Tasks, opts ...grpc.CallOption) (*SingleStatus, error) {
	out := new(SingleStatus)
	err := grpc.Invoke(ctx, "/task_rpc_config.Task/InsertTasks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Task service

type TaskServer interface {
	QueryTasks(context.Context, *Params) (*Tasks, error)
	InsertTasks(context.Context, *Tasks) (*SingleStatus, error)
}

func RegisterTaskServer(s *grpc.Server, srv TaskServer) {
	s.RegisterService(&_Task_serviceDesc, srv)
}

func _Task_QueryTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).QueryTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task_rpc_config.Task/QueryTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).QueryTasks(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_InsertTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tasks)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).InsertTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task_rpc_config.Task/InsertTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).InsertTasks(ctx, req.(*Tasks))
	}
	return interceptor(ctx, in, info, handler)
}

var _Task_serviceDesc = grpc.ServiceDesc{
	ServiceName: "task_rpc_config.Task",
	HandlerType: (*TaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryTasks",
			Handler:    _Task_QueryTasks_Handler,
		},
		{
			MethodName: "InsertTasks",
			Handler:    _Task_InsertTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2f, 0x49, 0x2c, 0xce, 0x8e, 0x2f,
	0x2a, 0x48, 0x8e, 0x87, 0x08, 0x2b, 0xa9, 0x71, 0xb1, 0x05, 0x24, 0x16, 0x25, 0xe6, 0x16, 0x0b,
	0xc9, 0x70, 0x71, 0x42, 0x58, 0xc1, 0x25, 0x45, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x08,
	0x01, 0x25, 0x45, 0x2e, 0xd6, 0x90, 0xc4, 0xe2, 0xec, 0x62, 0x21, 0x09, 0x2e, 0x76, 0xe7, 0xfc,
	0xbc, 0x92, 0xd4, 0xbc, 0x12, 0xa8, 0x22, 0x18, 0x57, 0x49, 0x8f, 0x8b, 0x27, 0x38, 0x33, 0x2f,
	0x3d, 0x27, 0x35, 0xb8, 0x24, 0xb1, 0xa4, 0xb4, 0x58, 0x48, 0x8e, 0x8b, 0xcb, 0xb5, 0xa8, 0xc8,
	0x37, 0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x15, 0xaa, 0x18, 0x49, 0xc4, 0xa8, 0x9f, 0x91, 0x8b, 0x05,
	0x64, 0xa6, 0x90, 0x3d, 0x17, 0x57, 0x60, 0x69, 0x6a, 0x51, 0x25, 0xc4, 0x02, 0x71, 0x3d, 0x34,
	0x37, 0xea, 0x41, 0x5c, 0x21, 0x25, 0x86, 0x21, 0x01, 0xd6, 0xa0, 0xc4, 0x20, 0xe4, 0xc6, 0xc5,
	0xed, 0x99, 0x57, 0x9c, 0x5a, 0x54, 0x02, 0x31, 0x01, 0x87, 0x42, 0x29, 0x59, 0x0c, 0x71, 0x64,
	0xf7, 0x2a, 0x31, 0x38, 0x49, 0x70, 0xb1, 0x67, 0xe6, 0x83, 0x15, 0x3b, 0x71, 0x3b, 0x83, 0x55,
	0x04, 0x80, 0x42, 0x2d, 0x80, 0x31, 0x89, 0x0d, 0x1c, 0x7c, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x9f, 0x79, 0x64, 0x03, 0x4e, 0x01, 0x00, 0x00,
}
